template = "https://github.com/giellalt/template-lang-und"
rev_id = 305
template_sha = "64df68fecb78cef7f709bfe67c09affe7c3b0c38"

[replacements]
__GLOTTOLOG_ID__ = "kekc1242"
__REPO__ = "lang-kek"
__UND2C__ = "kek"
__UNDEFINED__ = "Kekchí"
__UND__ = "kek"
