template = "https://github.com/giellalt/template-lang-und"
rev_id = 307
template_sha = "6f7d35fea20007282cb2085308400ab4050d8be7"

[replacements]
__GLOTTOLOG_ID__ = "kekc1242"
__REPO__ = "lang-kek"
__UND2C__ = "kek"
__UNDEFINED__ = "Kekchí"
__UND__ = "kek"
