[package]
name = "kek"
human_name = "Kekchí"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.kek]
filename = "kek-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-kek"
platform = "windows"
uuid = "5A343EE8-9067-4A3E-973B-D4A0A89C4670"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.kek"
package = "speller-kek"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-kek-mso"
platform = "windows"
uuid = "DE7DBDE6-A14D-4C96-9933-0766DC25A840"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-kek"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
